export const makeHosData = [
  {
    pageProps: {
      user: {
        id: 0,
        nickName: null,
        sex: null,
        profileImage: null,
        level: 0,
        birthYear: 0,
        country: null,
      },
      authorization: "563deb5d469e4057b235766226750ca4",
      query: {
        category: "눈성형",
        country: "kr",
      },
      language: "ko-KR",
      title: "이벤트 | 강남언니 - 1등 성형수술&피부시술 정보앱 | 눈성형",
      data: {
        events: {
          reason: "SUCCESS",
          data: [
            {
              id: 37232,
              titleImage:
                "https://image2.gnsister.com/images/direct/1715822401433_13c1df19ac874491a7a6472bc7f1abe6.png?originalImageWidth=1080&originalImageHeight=1080",
              title: "어반 _ 토탈 눈성형",
              hospitalId: 4256,
              hospitalName: "어반성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 139,
              discountedCost: 429000,
              cost: 429000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1661884051000,
            },
            {
              id: 56811,
              titleImage:
                "https://image2.gnsister.com/images/direct/1693468226114_dc57c0971ab44f7b8c7b6debab446df0.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "리앤리_비절개 중년 쌍꺼풀",
              hospitalId: 2159,
              hospitalName: "리앤리성형외과",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 42,
              discountedCost: 759000,
              cost: 759000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1693437616000,
            },
            {
              id: 63634,
              titleImage:
                "https://image2.gnsister.com/images/direct/1700467640821_29c28d6e02a84104aaf65d147f411911.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "환승프리티&이에스자연유착",
              hospitalId: 4277,
              hospitalName: "이에스청담성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 38,
              discountedCost: 649000,
              cost: 649000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1700442091000,
            },
            {
              id: 55464,
              titleImage:
                "https://image2.gnsister.com/images/direct/1712815228728_e492d57ef8524f42983ba05fc4d81b45.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "리아이_진심자연유착",
              hospitalId: 5160,
              hospitalName: "리아이성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 26,
              discountedCost: 539000,
              cost: 539000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1690766341000,
            },
            {
              id: 75132,
              titleImage:
                "https://image2.gnsister.com/images/direct/1709195855311_1d0b0742c44f4021b1b0c2995f19c7d9.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "인트로 원데이 눈성형",
              hospitalId: 5280,
              hospitalName: "인트로성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "서초구",
              rating: 10,
              ratingCount: 26,
              discountedCost: 649000,
              cost: 649000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1707861939000,
            },
            {
              id: 55465,
              titleImage:
                "https://image2.gnsister.com/images/direct/1712815331760_5815610160c643429cd4614dabcb2434.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "리아이_진심눈재수술",
              hospitalId: 5160,
              hospitalName: "리아이성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 23,
              discountedCost: 979000,
              cost: 979000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1690766852000,
            },
            {
              id: 13591,
              titleImage:
                "https://image2.gnsister.com/images/direct/1691742939346_3bfd135a2d914c7589ddf7fb1f4744fc.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "빠른회복 하이브리드 쌍꺼풀",
              hospitalId: 2159,
              hospitalName: "리앤리성형외과",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 24,
              discountedCost: 1199000,
              cost: 1199000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1596041043000,
            },
            {
              id: 21997,
              titleImage:
                "https://image2.gnsister.com/images/direct/1700982118641_d626317162bd4a4999900cf833c4e8b6.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "라스트 눈재수술, 마지막 눈성형 쌍꺼풀재수술 ",
              hospitalId: 3391,
              hospitalName: "라스트성형외과",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 27,
              discountedCost: 869000,
              cost: 869000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1626885211000,
            },
            {
              id: 64302,
              titleImage:
                "https://image2.gnsister.com/images/direct/1714641616242_fc1d2f83111c4af9858a90efbf0721bd.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "인트로_엄마눈성형_상안검_하안검",
              hospitalId: 5280,
              hospitalName: "인트로성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "서초구",
              rating: 10,
              ratingCount: 15,
              discountedCost: 1199000,
              cost: 1199000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1701105744000,
            },
            {
              id: 81225,
              titleImage:
                "https://image2.gnsister.com/images/direct/1714638470020_842577670c8e4ecd8265c7dc646f3049.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "내마음대로&ES.쌍꺼풀끝라인올리기",
              hospitalId: 4277,
              hospitalName: "이에스청담성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 6,
              discountedCost: 319000,
              cost: 319000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1714608625000,
            },
            {
              id: 51387,
              titleImage:
                "https://image2.gnsister.com/images/direct/1706590620518_cf0c0e07c62d494e97114d7929861b5e.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "앤드 남자 무쌍 눈매교정",
              hospitalId: 2699,
              hospitalName: "앤드성형외과",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 32,
              discountedCost: 539000,
              cost: 869000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "GROWTH",
              createTime: 1686602829000,
            },
            {
              id: 15414,
              titleImage:
                "https://image2.gnsister.com/images/direct/1690268600074_eb8ad2345898471ea3e2b843412c65d4.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "마이티 절개 눈재수술",
              hospitalId: 3005,
              hospitalName: "마이티성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 12,
              discountedCost: 1500000,
              cost: 1500000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1606255601000,
            },
            {
              id: 59206,
              titleImage:
                "https://image2.gnsister.com/images/direct/1701050898253_42a76fcacdb44336ab54ea10e8f66fe0.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "인트로 눈재수술 ",
              hospitalId: 5280,
              hospitalName: "인트로성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "서초구",
              rating: 10,
              ratingCount: 13,
              discountedCost: 979000,
              cost: 979000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1696955291000,
            },
            {
              id: 80274,
              titleImage:
                "https://image2.gnsister.com/images/direct/1713408277366_3040713793cd4e5f9d1aa0005e759f7f.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "어반 _ 남자 무쌍 눈매교정 ",
              hospitalId: 4256,
              hospitalName: "어반성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 3,
              discountedCost: 649000,
              cost: 649000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1713378684000,
            },
            {
              id: 60315,
              titleImage:
                "https://image2.gnsister.com/images/direct/1698113810545_2f532c27193844559bfe163e7af5f81e.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "온에어 비절개눈매교정",
              hospitalId: 3403,
              hospitalName: "온에어성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 2,
              discountedCost: 539000,
              cost: 539000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1698095383000,
            },
            {
              id: 81061,
              titleImage:
                "https://image2.gnsister.com/images/direct/1714375663774_d47a7f7389414327a378306570fd3cac.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "더 퍼스트 자연유착",
              hospitalId: 4227,
              hospitalName: "일미리성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "서초구",
              rating: 10,
              ratingCount: 9,
              discountedCost: 440000,
              cost: 440000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "GROWTH",
              createTime: 1714413669000,
            },
            {
              id: 76532,
              titleImage:
                "https://image2.gnsister.com/images/direct/1709786351674_3cc545f5d250463e839091bcb947d755.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "퀵 7포인트 매몰 쌍꺼풀",
              hospitalId: 173,
              hospitalName: "CDU청담유성형외과",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 4,
              discountedCost: 430000,
              cost: 430000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1709758820000,
            },
            {
              id: 78717,
              titleImage:
                "https://image2.gnsister.com/images/direct/1710989334750_3acceb4879d74ee898badef01bf3d745.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "어반 _마지막 눈 재수술 ",
              hospitalId: 4256,
              hospitalName: "어반성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 5,
              discountedCost: 759000,
              cost: 759000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1710960894000,
            },
            {
              id: 78736,
              titleImage:
                "https://image2.gnsister.com/images/direct/1711008785033_cd104ee6c1f84f42bd001843658c116a.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "어반_ 중년 눈성형 ",
              hospitalId: 4256,
              hospitalName: "어반성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 7,
              discountedCost: 990000,
              cost: 990000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1710979059000,
            },
            {
              id: 22662,
              titleImage:
                "https://image2.gnsister.com/images/direct/1630041457747_841d0b59296a4197b21e6064d1f6b467.jpg?originalImageWidth=1080&originalImageHeight=1080",
              title: "더비비 자연유착",
              hospitalId: 3423,
              hospitalName: "더비비성형외과의원",
              hospitalSubway: null,
              hospitalSido: "서울",
              hospitalCountry: "KR",
              hospitalSiGunGu: "강남구",
              rating: 10,
              ratingCount: 8,
              discountedCost: 440000,
              cost: 440000,
              currency: "KRW",
              showVatBadge: true,
              useBuyNow: false,
              assessmentState: "CERTIFIED",
              createTime: 1630012617000,
            },
          ],
          start: 0,
          length: 20,
          recordsTotal: 718,
          recordsFiltered: 718,
        },
        categories: [
          {
            id: 413,
            name: "눈성형",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/eye_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/eye_on.png",
          },
          {
            id: 412,
            name: "코성형",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/nose_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/nose_on.png",
          },
          {
            id: 414,
            name: "안면윤곽/양악",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/faceline_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/faceline_on.png",
          },
          {
            id: 421,
            name: "가슴성형",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/breast_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/breast_on.png",
          },
          {
            id: 422,
            name: "지방성형",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/bodyline_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/bodyline_on.png",
          },
          {
            id: 416,
            name: "필러",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/filler_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/filler_on.png",
          },
          {
            id: 415,
            name: "보톡스",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/botox_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/botox_on.png",
          },
          {
            id: 419,
            name: "리프팅",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/transplant_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/transplant_on.png",
          },
          {
            id: 411,
            name: "피부",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/acne_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/acne_on.png",
          },
          {
            id: 537,
            name: "제모",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/waxing_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/waxing_on.png",
          },
          {
            id: 418,
            name: "모발이식",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/hair_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/hair_on.png",
          },
          {
            id: 420,
            name: "치아",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/teethandoptical_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/teethandoptical_on.png",
          },
          {
            id: 417,
            name: "한방",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/oriental_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/oriental_on.png",
          },
          {
            id: 423,
            name: "기타",
            normalIconUrl:
              "https://image2.gnsister.com/images/icon/etc_off.png",
            selectedIconUrl:
              "https://image2.gnsister.com/images/icon/etc_on.png",
          },
        ],
        defaultText: {
          discountedCost: "특가",
        },
      },
      cookies: {
        token: "563deb5d469e4057b235766226750ca4",
        _gid: "GA1.2.1162220716.1716946582",
        _fbp: "fb.1.1716946582373.1867140951",
        _gcl_au: "1.1.312850047.1716946583",
        _tt_enable_cookie: "1",
        _ttp: "8LLGYLsc8kRYJmSjDZi4tdY9iTw",
        ab180ClientId: "341eb381-2ad1-4043-a757-710b7c5d7d33",
        _ga: "GA1.2.1412374287.1716946582",
        _gat_gtag_UA_58727275_12: "1",
        _ga_GXB8082VP1: "GS1.1.1716946583.1.1.1716947266.60.0.0",
        airbridge_session:
          '{"id":"84fb0d72-7f09-4ee0-ad49-a21ea96ad3eb","timeout":1800000,"start":1716946583998,"end":1716947267643}',
        _gat: "1",
        _dd_s: "rum=0&expire=1716948172047",
        "amplitude_id_ee9e97f46fa77da052305bb94e327b88gangnamunni.com":
          "eyJkZXZpY2VJZCI6ImRlMDJiZjdlLWJiZTktNDA0Yi1hNWQyLWVkYjdjOTlhMDI5NFIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTcxNjk0NjU4MjI2OCwibGFzdEV2ZW50VGltZSI6MTcxNjk0NzI3Mjg0OCwiZXZlbnRJZCI6MTYsImlkZW50aWZ5SWQiOjAsInNlcXVlbmNlTnVtYmVyIjoxNn0=",
      },
      canonical: "https://www.gangnamunni.com/events",
      meta: {
        description:
          "국내 1위 성형정보앱 강남언니. 리얼후기부터 가격비교, 상담예약까지 한번에. 강남언니를 지금 만나보세요.",
        image: "https://www.gangnamunni.com/images/kr/meta_thumb_02.jpg",
        locale: "ko_KR",
        name: "강남언니",
        title: "이벤트 | 강남언니 - 1등 성형수술&피부시술 정보앱 | 눈성형",
        twtCardType: "summary_large_image",
        type: "website",
      },
    },
    __N_SSP: true,
  },
];
